// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecipeShare.Library.EntityFramework;

#nullable disable

namespace RecipeShare.Library.EntityFramework.Migrations
{
    [DbContext(typeof(RecipeShareDbContext))]
    partial class RecipeShareDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecipeShare.Library.Models.Entities.DietaryTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RId");

                    b.ToTable("DietaryTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "High Protein",
                            RId = 1
                        },
                        new
                        {
                            Id = 2,
                            Name = "Vegan",
                            RId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "Gluten-Free",
                            RId = 2
                        },
                        new
                        {
                            Id = 4,
                            Name = "Low Carb",
                            RId = 3
                        },
                        new
                        {
                            Id = 5,
                            Name = "Gluten-Free",
                            RId = 3
                        });
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Entities.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spaghetti",
                            Quantity = 200m,
                            RId = 1,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Minced Beef",
                            Quantity = 300m,
                            RId = 1,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tomato Sauce",
                            Quantity = 150m,
                            RId = 1,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Onion",
                            Quantity = 1m,
                            RId = 1,
                            Unit = "unit"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chickpeas",
                            Quantity = 400m,
                            RId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Coconut Milk",
                            Quantity = 200m,
                            RId = 2,
                            Unit = "ml"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Curry Powder",
                            Quantity = 2m,
                            RId = 2,
                            Unit = "tsp"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Spinach",
                            Quantity = 100m,
                            RId = 2,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Chicken Breast",
                            Quantity = 250m,
                            RId = 3,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Mixed Greens",
                            Quantity = 100m,
                            RId = 3,
                            Unit = "g"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Cherry Tomatoes",
                            Quantity = 10m,
                            RId = 3,
                            Unit = "units"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Olive Oil",
                            Quantity = 1m,
                            RId = 3,
                            Unit = "tbsp"
                        });
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Entities.Step", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.Property<int>("StepNumber")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RId");

                    b.ToTable("Steps");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            RId = 1,
                            StepNumber = 1,
                            Text = "Boil spaghetti until al dente."
                        },
                        new
                        {
                            Id = 2,
                            RId = 1,
                            StepNumber = 2,
                            Text = "Cook minced beef in a pan until browned."
                        },
                        new
                        {
                            Id = 3,
                            RId = 1,
                            StepNumber = 3,
                            Text = "Add onion and tomato sauce. Simmer."
                        },
                        new
                        {
                            Id = 4,
                            RId = 1,
                            StepNumber = 4,
                            Text = "Serve sauce over spaghetti."
                        },
                        new
                        {
                            Id = 5,
                            RId = 2,
                            StepNumber = 1,
                            Text = "Sauté spices."
                        },
                        new
                        {
                            Id = 6,
                            RId = 2,
                            StepNumber = 2,
                            Text = "Add chickpeas and coconut milk."
                        },
                        new
                        {
                            Id = 7,
                            RId = 2,
                            StepNumber = 3,
                            Text = "Simmer and add spinach."
                        },
                        new
                        {
                            Id = 8,
                            RId = 2,
                            StepNumber = 4,
                            Text = "Serve hot with rice."
                        },
                        new
                        {
                            Id = 9,
                            RId = 3,
                            StepNumber = 1,
                            Text = "Grill chicken until cooked through."
                        },
                        new
                        {
                            Id = 10,
                            RId = 3,
                            StepNumber = 2,
                            Text = "Toss greens and tomatoes in a bowl."
                        },
                        new
                        {
                            Id = 11,
                            RId = 3,
                            StepNumber = 3,
                            Text = "Top with sliced chicken and drizzle olive oil."
                        });
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CookingTime")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CookingTime = 45,
                            Title = "Classic Spaghetti Bolognese"
                        },
                        new
                        {
                            Id = 2,
                            CookingTime = 30,
                            Title = "Vegan Chickpea Curry"
                        },
                        new
                        {
                            Id = 3,
                            CookingTime = 20,
                            Title = "Grilled Chicken Salad"
                        });
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Entities.DietaryTag", b =>
                {
                    b.HasOne("RecipeShare.Library.Models.Recipe", "Recipe")
                        .WithMany("DietaryTags")
                        .HasForeignKey("RId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Entities.Ingredient", b =>
                {
                    b.HasOne("RecipeShare.Library.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Entities.Step", b =>
                {
                    b.HasOne("RecipeShare.Library.Models.Recipe", "Recipe")
                        .WithMany("Steps")
                        .HasForeignKey("RId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("RecipeShare.Library.Models.Recipe", b =>
                {
                    b.Navigation("DietaryTags");

                    b.Navigation("Ingredients");

                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
